bookmark/urls.py
from django.conf.urls import url
from django.contrib import admin
from .views import *

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', BookmarkListV.as_view(), name='index'),
    url(r'^(?P<pk>\d+)/$', BookmarkDetailV.as_view(), name='detail'),
    url(r'^create/$', BookmarkCreateV.as_view(), name='create'),
    url(r'^update/(?P<pk>\d+)/$', BookmarkUpdateV.as_view(), name='update'),
    url(r'^delete/(?P<pk>\d+)/$', BookmarkDeleteV.as_view(), name='delete'),
]

mybookmark/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from .views import IndexPage

urlpatterns = [
    url(r'^$', IndexPage.as_view(), name="index"),
    url(r'^admin/', admin.site.urls),
    url(r'bookmark/', include("bookmark.urls", namespace="bookmark")),
]

bookmark/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Bookmark(models.Model):
    author = models.ForeignKey(User, null=True)
    title = models.CharField(max_length=100, blank=True, null=True)
    url = models.URLField('url', unique=True)

    def __str__(self):
        return self.title

bookmark/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from .models import Bookmark
from django.core.urlresolvers import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin

# Create your views here.
class BookmarkListV(LoginRequiredMixin, ListView):
    model = Bookmark

class BookmarkDetailV(LoginRequiredMixin, DetailView):
    model = Bookmark

class BookmarkCreateV(LoginRequiredMixin, CreateView):
    model = Bookmark
    fields = ['title', 'url']
    success_url = reverse_lazy('bookmark:index')

    def form_valid(self, form):
        form.instance.author_id = self.request.user.id
        if form.is_valid():
            form.instance.save()
            return redirect('/bookmark/')
        else:
            return self.render_to_response({'form':form})

class BookmarkUpdateV(LoginRequiredMixin, UpdateView):
    model = Bookmark
    fields = ['title', 'url']
    success_url = reverse_lazy('bookmark:index')

class BookmarkDeleteV(LoginRequiredMixin, DeleteView):
    model = Bookmark
    success_url = reverse_lazy('bookmark:index')

mybookmark/views.py
from django.views.generic.base import TemplateView

class IndexPage(TemplateView):
    template_name = "index.html"

bookmark/templates/bookmark/bookmark_confirm_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Delete Bookmark</title>
</head>
<body>
    <h1>Delete this site?</h1>
        <form action="." method="post">
            {% csrf_token %}
            <p>
                Do you really want to delete {{object}} ?
            </p>
            <input type="submit" value="Delete">
        </form>
</body>
</html>

bookmark/templates/bookmark/bookmark_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Bookmark Detail</title>
</head>
<body>
    <h1>Bookmark Detail</h1>
    <h4><a href="{{object.url}}" target="" _blank>{{object.url}}</a></h4>
</body>
</html>

bookmark/templates/bookmark/bookmark_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Bookmark Create</title>
</head>
<body>
    <h1>Bookmark Create Page</h1>
        <form action="." method="post">
            {% csrf_token %}
            {{form.as_p}}
            <input type="submit" value="OK">
        </form>
</body>
</html>

bookmark/templates/bookmark/bookmark_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Bookmark List</title>
</head>
<body>
    <h1>Bookmark List</h1>
        <ul>
            {% for bookmark in object_list %}
            <li>
                <a href="{% url 'bookmark:detail' bookmark.id %}">{{bookmark}}</a>
                <a href="{% url 'bookmark:update' bookmark.id %}">수정</a>
                <a href="{% url 'bookmark:delete' bookmark.id %}">삭제</a>
            </li>
            {% endfor %}
        </ul>
</body>
</html>

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Django First Application</title>
</head>
<body>
    <h1>Hello my first application</h1>
    <a href="{% url 'bookmark:index' %}">Bookmark Page</a>
</body>
</html>